#
#  КОНФИГ НЕ ИЗМЕНЯТЬ! ОН ПОДКАЧИВАЕТСЯ С ГИТХАБА
#
#  Разработчик: DarthBoomerPlay_
#  Сайт Разработчика: darthboomerplay.github.io
#

kits:
 test:
   type: normal
   name: 'Тестовый кит'
   cost: 2500
